spring:
  datasource:
    url: jdbc:sqlite:./data/test.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1

  # JPA / Hibernate 설정
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: true   # 콘솔 출력
    properties:
      hibernate:
        format_sql: true     # 줄바꿈 + 정렬
        highlight_sql: true  # 색상 강조 (콘솔)

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace