spring:
  datasource:
    url: jdbc:sqlite:/Users/jeong-yeonghan/work/sqlite-tools-osx-arm64-3510300/test.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1

  # JPA / Hibernate 설정
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true